---
title: "Crimes"
author: "Yu-Chun Chien"
date: "7/10/2021"
output: pdf_document
---

```{r, warning=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(plotly)
library(ggrepel)
```

# I. Import Datasets

```{r, warning =FALSE}
# import data
shooting <- read_csv("Shooting Occurrences (2014-2019).csv")
victims <- read_csv("Victims of Crime (2014-2019).csv")
unemployment <- read_csv("1410029401_databaseLoadingData.csv")
homicide <- read_csv("3510007101_databaseLoadingData.csv")
indicators <- read_csv("Major_Crime_Indicators.csv")
```

# II. First Plot: Crime rate vs. Unemployment rate

```{r}
# get toronto data for unemployment
trimmed <- 0
trimmed <- subset(unemployment, GEO == "Toronto, Ontario")

# data cleaning for unemployment 
reportedyear <- c(2014, 2015, 2016, 2017, 2018, 2019, 2020)
first <- mean(trimmed$VALUE[1:5])
sec <- mean(trimmed$VALUE[6:17])
third <- mean(trimmed$VALUE[18:29])
fourth <- mean(trimmed$VALUE[30:41])
five <- mean(trimmed$VALUE[42:53])
six <- mean(trimmed$VALUE[54:65])
seven <- mean(trimmed$VALUE[66:77])
rate <- c(first, sec, third, fourth, five, six, seven)
df <- data.frame(reportedyear, rate)

```

```{r}

# first plot 
ggplot() + geom_bar(aes(reportedyear, fill = MCI), data = indicators)+ geom_line(aes(reportedyear, rate * 5000), data = df) + scale_y_continuous(name = "Number of Crimes", sec.axis =  sec_axis(~. / 5000, name = "unemployment rate"))+ labs(x = "Year", title = "Crimes & Unemployment Rate from 2014 - 2020", caption = "Source: Statistics Canada") + scale_fill_discrete(name = "Type of Crime") + geom_label(data = df, aes(x = reportedyear, y = rate * 5080, label = round(rate, 2)), size = 4, fontface = "bold") + geom_text(aes(x=2016, label="unemployment rate", y=37500), size=5, color="black") + theme_classic()

```

# III. Second Plot: Homicide Rate of 5 Biggest Cities in North America


```{r}
#la data 
year_la <- c(2015, 2016, 2017, 2018, 2019)
la_value <- c(5.8, 6.1, 5.7, 5.6, 5.0)
la <- data.frame(year_la, la_value)

# nyc data
year_nyc <- c(2015, 2016, 2017, 2018, 2019)
nyc_value <- round(c(352*100000/8419000, 335*100000/8419000, 292*100000/8419000, 295*100000/8419000, 319*100000/8419000), 1)
nyc <- data.frame(year_nyc, nyc_value)

# chicago data
year_chi <- c(2015, 2016, 2017, 2018, 2019)
chi_value <- round(c(468*100000/2710000, 756*100000/2710000, 650*100000/2710000, 567*100000/2710000, 492*100000/2710000), 1)
chi <- data.frame(year_chi, chi_value)

# making dataframe for US data
GEO <- c("Los Angeles", "Los Angeles",  "Los Angeles", "Los Angeles", "Los Angeles", "New York City", "New York City", "New York City", "New York City", "New York City", "Chicago", "Chicago", "Chicago", "Chicago", "Chicago")
REF_DATE <- c(year_la, year_nyc, year_chi)
VALUE <- c(la_value, nyc_value, chi_value)
us_crime <- data.frame(REF_DATE, GEO, VALUE)

# subsetting Toronto and Montreal data
toptwo_canada <- subset(homicide, GEO == "Toronto, Ontario"| GEO == "Montréal, Quebec")
toptwo_canada <- subset(toptwo_canada, select = c(REF_DATE, GEO, VALUE))

# combining Canada and US data
North_america <- rbind(us_crime, toptwo_canada)

```


# IV. Third Plot: Number of Victims of Different Crimes by Age and Sex

```{r}
victims <- subset(victims, Sex == "F"|Sex == "M")

ggplot(victims, aes(AgeCohort, Count_, fill = Sex)) + geom_col(position = "dodge") + facet_grid(~Subtype) + scale_fill_manual(values = c("#00AFBB", "#E7B800")) + labs(x = "Age", y = "Number of Cases", title = "Number of Victims of Different Crimes by Age and Sex", caption = "Source: Toronto Open Data Portal") + scale_fill_discrete(name = "Sex", labels = c("Female", "Male")) +theme_classic()
```

# V. Fourth Plot: Visualizing Percentage by People Icon

```{r}
# sexual violation female victims
num <- which(victims$Subtype == "Sexual Violation" & victims$Sex=="F")
num_sex<- which(victims$Subtype == "Sexual Violation")
sum(victims[num,10])/sum(victims[num_sex,10])
```

```{r}
# robbery male victims
numb <- which(victims$Subtype == "Robbery" & victims$Sex=="M")
numb_sex<- which(victims$Subtype == "Robbery")
sum(victims[numb,10])/sum(victims[numb_sex,10])
```

```{r}
# percentage of assault cases
number <- which(victims$Subtype == "Assault")
sum(victims[number,10])/sum(victims[,10])
```
